name: Initialize Project Folder Structure

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Clean repository (except .git and .github)
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '.github' -exec rm -rf {} +

      - name: Create all base folders
        run: |
          mkdir -p assets/images
          mkdir -p assets/icons
          mkdir -p assets/sounds
          mkdir -p lessons/grade1
          mkdir -p lessons/grade2
          mkdir -p lessons/grade3
          mkdir -p lessons/grade4
          mkdir -p lessons/grade5
          mkdir -p lessons/grade6
          mkdir -p games
          mkdir -p css
          mkdir -p js
          mkdir -p components

      - name: Commit folders creation
        run: |
          git config user.email "abc-explorer@now.com"
          git config user.name "ABC Explorer Bot"
          git add .
          git commit -m "🏛️ Initialize project folder structure"
          git push
